(()=>{'use strict';
const DB='PersonalLifePlannerFinal',VER=2,STORE='records';let db,records=[],tab='today',timer;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date(), today=()=>{let d=now();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fa=n=>Number(n||0).toLocaleString('fa-IR');
const fdate=iso=>new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'medium'}).format(new Date(String(iso).slice(0,10)+'T12:00:00'));
const active=()=>records.filter(r=>!r.deletedAt), type=t=>active().filter(r=>r.type===t);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function openDB(){return new Promise((ok,bad)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{let d=r.result,s=d.objectStoreNames.contains(STORE)?r.transaction.objectStore(STORE):d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('type','type');s.createIndex('date','date');s.createIndex('updatedAt','updatedAt')};r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>bad(r.error)})}
const getAll=()=>new Promise((ok,bad)=>{let r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});
const put=x=>new Promise((ok,bad)=>{let r=db.transaction(STORE,'readwrite').objectStore(STORE).put(x);r.onsuccess=()=>ok(x);r.onerror=()=>bad(r.error)});
async function save(type,data,date=today()){let r={id:uid(),type,data,date,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),schemaVersion:1,revision:1};await put(r);records.push(r);return r}
async function update(r,data,date=r.date){r.data={...r.data,...data};r.date=date;r.updatedAt=new Date().toISOString();r.revision++;await put(r);records=records.map(x=>x.id===r.id?r:x)}
async function trash(r){r.deletedAt=new Date().toISOString();r.updatedAt=r.deletedAt;r.revision++;await put(r);records=records.map(x=>x.id===r.id?r:x)}
async function restore(r){delete r.deletedAt;r.updatedAt=new Date().toISOString();r.revision++;await put(r);records=records.map(x=>x.id===r.id?r:x)}
function toast(s){clearTimeout(timer);let e=document.createElement('div');e.className='notice';e.textContent=s;document.body.appendChild(e);timer=setTimeout(()=>e.remove(),2500)}
function layout(){document.body.innerHTML=`<div class="app"><header class="top"><div class="brand"><div><h1>دفتر زندگی</h1><small>محلی · خصوصی · بدون تبلیغات</small></div><button class="btn" id="lock">🔒</button></div><input class="search" id="search" placeholder="جستجو در اطلاعات غیرخصوصی…"></header><main class="content" id="content"></main><button class="fab" id="fab">+</button><nav class="nav"><div class="nav-inner">${[['today','🏠','امروز'],['finance','💰','مالی'],['habits','✓','عادت‌ها'],['events','👥','وقایع'],['more','☰','بیشتر']].map(x=>`<button data-tab="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div></nav></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('#fab').onclick=quick;$('#search').oninput=e=>search(e.target.value);$('#lock').onclick=appLock;render()}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let c=$('#content');c.innerHTML=tab==='today'?todayView():tab==='finance'?financeView():tab==='habits'?habitView():tab==='events'?eventView():moreView();bind()}
function todayView(){let d=today(),ex=type('expense').filter(r=>r.date===d),ev=type('event').filter(r=>r.date===d),hl=type('habitLog').filter(r=>r.date===d),jr=type('journal').filter(r=>r.date===d);return `<section class="panel hero"><h2>${fdate(d)}</h2><p class="muted">ثبت سریع امروز؛ جزئیات فقط وقتی لازم است.</p><div class="cards"><div class="card"><b>${fa(ex.reduce((a,r)=>a+Number(r.data.amount||0),0))}</b><span>هزینه امروز</span></div><div class="card"><b>${ev.length}</b><span>واقعه</span></div><div class="card"><b>${hl.length}</b><span>عادت انجام‌شده</span></div><div class="card"><b>${jr.length}</b><span>یادداشت خصوصی</span></div></div></section><section class="panel"><h3>ثبت سریع</h3><div class="actions"><button class="btn primary" data-quick="expense">💸 هزینه</button><button class="btn" data-quick="income">💵 درآمد</button><button class="btn" data-quick="transfer">↔️ انتقال</button><button class="btn" data-quick="event">👥 واقعه</button><button class="btn" data-quick="journal">🔒 یادداشت</button></div></section><section class="panel"><h3>خط زمانی امروز</h3>${[...ev,...ex].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(r=>r.type==='event'?eventRow(r):txRow(r)).join('')||'<p class="muted">امروز هنوز چیزی ثبت نشده.</p>'}</section>`}
function financeView(){let ex=type('expense'),inc=type('income'),tr=type('transfer'),fee=type('fee'),sum=a=>a.reduce((n,r)=>n+Number(r.data.amount||0),0);let rows=[...ex,...inc,...tr,...fee].sort((a,b)=>b.date.localeCompare(a.date));return `<section class="panel"><h2>مالی</h2><div class="cards"><div class="card"><b>${fa(sum(ex))}</b><span>هزینه</span></div><div class="card"><b>${fa(sum(inc))}</b><span>درآمد</span></div><div class="card"><b>${fa(sum(fee))}</b><span>کارمزد</span></div><div class="card"><b>${fa(sum(inc)-sum(ex)-sum(fee))}</b><span>خالص</span></div></div><div class="actions"><button class="btn primary" data-quick="expense">+ هزینه</button><button class="btn" data-quick="income">+ درآمد</button><button class="btn" data-quick="transfer">↔ انتقال</button><button class="btn" data-quick="fee">+ کارمزد</button></div></section><section class="panel"><h3>تراکنش‌ها</h3>${rows.slice(0,50).map(txRow).join('')||'<p class="muted">تراکنشی ثبت نشده.</p>'}</section>`}
function txRow(r){let label={expense:'هزینه',income:'درآمد',transfer:'انتقال',fee:'کارمزد'}[r.type];return `<div class="row"><div class="row-main"><b>${esc(r.data.description||label)} <small>(${label})</small></b><small>${fdate(r.date)} · ${esc(r.data.source||'')}${r.data.destination?' → '+esc(r.data.destination):''}${r.data.category?' · '+esc(r.data.category):''}</small></div><strong class="amount">${fa(r.data.amount)}</strong><div class="row-actions"><button class="btn" data-edit="${r.id}">ویرایش</button><button class="btn danger" data-del="${r.id}">حذف</button></div></div>`}
function eventRow(r){return `<div class="row"><div class="row-main"><b>${esc(r.data.title)} ${r.data.important?'⭐':''}</b><small>${fdate(r.date)}${r.data.time?' · '+esc(r.data.time):''}${r.data.location?' · '+esc(r.data.location):''}${r.data.people?.length?' · '+esc(r.data.people.join('، ')):''}</small></div><div class="row-actions"><button class="btn" data-edit="${r.id}">ویرایش</button><button class="btn danger" data-del="${r.id}">حذف</button></div></div>`}
function habitView(){let hs=type('habit');return `<section class="panel"><h2>عادت‌ها</h2><button class="btn primary" data-newhabit>+ تعریف عادت</button>${hs.map(h=>{let done=type('habitLog').some(x=>x.data.habitId===h.id&&x.date===today());let logs=type('habitLog').filter(x=>x.data.habitId===h.id&&x.data.completed).length;return `<div class="row"><div class="row-main"><b>${esc(h.data.name)}</b><small>${esc(h.data.frequency)} · ${logs} ثبت انجام</small></div><button class="btn" data-habit="${h.id}">${done?'✓ انجام شد':'○ امروز'}</button><button class="btn" data-edit="${h.id}">ویرایش</button><button class="btn danger" data-del="${h.id}">حذف</button></div>`}).join('')||'<p class="muted">هنوز عادتی تعریف نشده.</p>'}</section>`}
function eventView(){let es=type('event').sort((a,b)=>b.date.localeCompare(a.date)),people={};es.forEach(e=>(e.data.people||[]).forEach(p=>people[p]=(people[p]||0)+1));return `<section class="panel"><h2>وقایع</h2><button class="btn primary" data-quick="event">+ واقعه</button><h3>افراد پرتکرار</h3><div class="chips">${Object.entries(people).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([p,n])=>`<span class="chip">${esc(p)} · ${n} بار</span>`).join('')||'<span class="muted">اطلاعاتی نیست.</span>'}</div><h3>Timeline</h3>${es.slice(0,60).map(eventRow).join('')||'<p class="muted">واقعه‌ای ثبت نشده.</p>'}</section>`}
function moreView(){let del=records.filter(r=>r.deletedAt);let deletedHtml=del.length?'<h3>اخیراً حذف‌شده</h3>'+del.slice(-20).reverse().map(r=>'<div class="row"><span>'+esc(r.data.description||r.data.title||r.type)+'</span><button class="btn" data-restore="'+r.id+'">بازیابی</button></div>').join(''):'';return '<section class="panel"><h2>تقویم شمسی</h2>'+calendarHtml()+'</section><section class="panel"><h2>تحلیل</h2>'+analytics()+'</section><section class="panel"><h2>یادداشت‌های خصوصی</h2>'+journalList()+'</section><section class="panel"><h2>داده و بازیابی</h2><p class="muted">Excel فقط برای مهاجرت اولیه است و در استفاده روزانه نقشی ندارد.</p><div class="actions"><button class="btn" data-export>خروجی JSON</button><button class="btn" data-import>ورود JSON</button></div><p class="status">فعال: '+active().length+' · حذف‌شده: '+del.length+'</p>'+deletedHtml+'</section>'}
function analytics(){let ex=type('expense'),by={};ex.forEach(r=>by[r.data.category||'سایر']=(by[r.data.category||'سایر']||0)+Number(r.data.amount||0));let arr=Object.entries(by).sort((a,b)=>b[1]-a[1]),max=arr[0]?.[1]||1;return `<div class="cards"><div class="card"><b>${fa(ex.reduce((a,r)=>a+Number(r.data.amount||0),0))}</b><span>کل هزینه</span></div><div class="card"><b>${type('event').length}</b><span>کل وقایع</span></div><div class="card"><b>${type('journal').length}</b><span>یادداشت خصوصی</span></div></div>${arr.slice(0,10).map(([k,v])=>`<div class="metric"><div class="row"><span>${esc(k)}</span><b>${fa(v)}</b></div><div class="bar"><i style="width:${Math.max(3,v/max*100)}%"></i></div></div>`).join('')||'<p class="muted">داده کافی نیست.</p>'}`}
function calendarHtml(){let d=now(), y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1),start=(first.getDay()+1)%7;let h='<div class="calhead">'+['ش','ی','د','س','چ','پ','ج'].map(x=>`<b>${x}</b>`).join('')+'</div><div class="calendar">';for(let i=0;i<start;i++)h+='<div class="day empty"></div>';for(let n=1;n<=days;n++){let iso=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,p=fdate(iso),ev=type('event').filter(r=>r.date===iso).length;h+=`<div class="day ${iso===today()?'today':''}"><b>${new Intl.NumberFormat('fa-IR').format(n)}</b><small>${esc(p)}</small>${ev?`<em>● ${ev}</em>`:''}</div>`}return h+'</div><p class="muted">تاریخ اصلی ذخیره‌سازی میلادی ISO است و نمایش فارسی/شمسی است.</p>'}
function journalList(){let js=type('journal').sort((a,b)=>b.date.localeCompare(a.date));return js.map(r=>`<div class="row"><div class="row-main"><b>🔒 یادداشت خصوصی</b><small>${fdate(r.date)}</small></div><button class="btn" data-openjournal="${r.id}">بازکردن</button><button class="btn danger" data-del="${r.id}">حذف</button></div>`).join('')||'<p class="muted">هنوز یادداشتی ثبت نشده.</p>'}
function quick(){showModal('ثبت سریع',`<div class="actions"><button class="btn primary" data-quick="expense">هزینه</button><button class="btn" data-quick="income">درآمد</button><button class="btn" data-quick="transfer">انتقال</button><button class="btn" data-quick="event">واقعه</button><button class="btn" data-quick="journal">یادداشت خصوصی</button></div>`)}
function showModal(title,body){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="sheet"><div class="sheet-head"><h2>${title}</h2><button class="btn" data-close>بستن</button></div>${body}</div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.remove();m.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{let t=b.dataset.quick;m.remove();formFor(t)});return m}
function formFor(t,r=null){if(t==='event')return eventForm(r);if(t==='journal')return journalForm();if(['expense','income','transfer','fee'].includes(t))return txForm(t,r);if(t==='habit')return habitForm(r)}
function txForm(t,r){let names={expense:'هزینه',income:'درآمد',transfer:'انتقال',fee:'کارمزد'},cats=['خوراک','خرید','حمل‌ونقل','قبوض','سلامت','سرگرمی','کار','کارمزد بانکی','سفر','آموزش','خودرو','مسکن','سایر'],src=['نقدی','ملت','سامان','پاسارگاد','رسالت','بلوبانک','مهر','سایر'];let d=r?.data||{};showModal(names[t],`<form id="txform"><div class="grid"><input class="input" name="amount" inputmode="numeric" value="${d.amount??''}" placeholder="مبلغ" required><input class="input" name="description" value="${esc(d.description||'')}" placeholder="شرح" required><input class="input" name="date" type="date" value="${r?.date||today()}"><select class="select" name="source">${src.map(x=>`<option ${d.source===x?'selected':''}>${x}</option>`).join('')}</select>${t==='expense'?`<select class="select" name="category">${cats.map(x=>`<option ${d.category===x?'selected':''}>${x}</option>`).join('')}</select>`:''}${t==='transfer'?`<select class="select" name="destination">${src.map(x=>`<option ${d.destination===x?'selected':''}>${x}</option>`).join('')}</select>`:''}<input class="input wide" name="tags" value="${esc((d.tags||[]).join('، '))}" placeholder="برچسب اختیاری"></div><div class="actions"><button class="btn primary">ذخیره</button></div></form>`);$('#txform').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),source=String(f.get('source')),dest=String(f.get('destination')||'');if(t==='transfer'&&source===dest)return toast('مبدأ و مقصد باید متفاوت باشند.');let data={amount:Number(String(f.get('amount')).replace(/,/g,'')),description:String(f.get('description')).trim(),source,category:f.get('category')||undefined,destination:t==='transfer'?dest:undefined,tags:String(f.get('tags')||'').split(/[,،]/).map(x=>x.trim()).filter(Boolean)};if(r)await update(r,data,String(f.get('date')));else await save(t,data,String(f.get('date')));document.querySelector('.modal')?.remove();render();toast('تراکنش ذخیره شد.')}}
function eventForm(r){let d=r?.data||{};showModal(r?'ویرایش واقعه':'واقعه سریع',`<form id="evform"><div class="grid"><input class="input wide" name="title" value="${esc(d.title||'')}" placeholder="عنوان واقعه (الزامی)" autofocus required><input class="input" name="date" type="date" value="${r?.date||today()}"><input class="input" name="time" type="time" value="${esc(d.time||'')}"><input class="input" name="people" value="${esc((d.people||[]).join('، '))}" placeholder="افراد: علی، مهدی"><input class="input" name="location" value="${esc(d.location||'')}" placeholder="مکان"><input class="input" name="category" value="${esc(d.category||'')}" placeholder="دسته"><input class="input wide" name="tags" value="${esc((d.tags||[]).join('، '))}" placeholder="برچسب‌ها"><textarea class="textarea wide" name="description" rows="3" placeholder="یادداشت کوتاه">${esc(d.description||'')}</textarea><label><input type="checkbox" name="important" ${d.important?'checked':''}> مهم</label></div><div class="actions"><button class="btn primary">ذخیره</button></div></form>`);$('#evform').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),data={title:String(f.get('title')).trim(),people:String(f.get('people')||'').split(/[,،]/).map(x=>x.trim()).filter(Boolean),location:String(f.get('location')||''),category:String(f.get('category')||''),tags:String(f.get('tags')||'').split(/[,،]/).map(x=>x.trim()).filter(Boolean),description:String(f.get('description')||''),important:f.get('important')==='on',time:String(f.get('time')||'')};if(r)await update(r,data,String(f.get('date')));else await save('event',data,String(f.get('date')));document.querySelector('.modal')?.remove();render();toast('واقعه ذخیره شد.')}}
function habitForm(r){let d=r?.data||{};showModal(r?'ویرایش عادت':'تعریف عادت',`<form id="hform"><input class="input" name="name" value="${esc(d.name||'')}" placeholder="مثلاً ۲۰ دقیقه مطالعه" required><select class="select" name="frequency"><option ${d.frequency==='روزانه'?'selected':''}>روزانه</option><option ${d.frequency==='هفتگی'?'selected':''}>هفتگی</option><option ${d.frequency==='ماهانه'?'selected':''}>ماهانه</option></select><div class="actions"><button class="btn primary">ذخیره</button></div></form>`);$('#hform').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),data={name:String(f.get('name')).trim(),frequency:String(f.get('frequency')),enabled:true};if(r)await update(r,data);else await save('habit',data);document.querySelector('.modal')?.remove();render();toast('عادت ذخیره شد.')}}
async function journalForm(){showModal('یادداشت خصوصی',`<div class="privacy"><b>🔒 خصوصی</b><p class="muted">متن در حالت عادی Preview نمی‌شود و قبل از ذخیره با AES-256-GCM رمزنگاری می‌شود.</p></div><form id="jform"><textarea class="textarea" name="text" rows="9" placeholder="فکر یا خاطره…" required></textarea><input class="input" name="pass" type="password" placeholder="رمز این یادداشت" required><div class="actions"><button class="btn primary">رمزنگاری و ذخیره</button></div></form>`);$('#jform').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target);await save('journal',{encrypted:await encrypt(String(f.get('text')),String(f.get('pass'))),private:true},today());document.querySelector('.modal')?.remove();render();toast('یادداشت رمزنگاری شد.')}catch{toast('ذخیره یادداشت ناموفق بود.')}}}
async function openJournal(r){showModal('بازکردن یادداشت خصوصی',`<p class="muted">متن تا وارد کردن رمز نمایش داده نمی‌شود.</p><input class="input" id="jpass" type="password" placeholder="رمز یادداشت"><div class="actions"><button class="btn primary" id="jopen">بازکردن</button></div><div id="jtext"></div>`);$('#jopen').onclick=async()=>{try{$('#jtext').textContent=await decrypt(r.data.encrypted,$('#jpass').value);toast('یادداشت باز شد.')}catch{$('#jtext').innerHTML='<p class="error">رمز اشتباه است یا داده آسیب دیده.</p>'}}}
async function encrypt(text,pass){let e=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey('raw',e.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,e.encode(text)));return `1.${b64(salt)}.${b64(iv)}.${b64(ct)}`}
async function decrypt(v,pass){let [,ss,is,cs]=v.split('.'),e=new TextEncoder(),salt=u8(ss),iv=u8(is),ct=u8(cs),base=await crypto.subtle.importKey('raw',e.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},key,ct))}
function b64(a){let s='';a.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}function u8(s){return Uint8Array.from(atob(s),x=>x.charCodeAt(0))}
function bind(){document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>formFor(b.dataset.quick));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{let r=records.find(x=>x.id===b.dataset.del);if(r){await trash(r);render();toast('حذف نرم انجام شد.')}});document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{let r=records.find(x=>x.id===b.dataset.restore);if(r){await restore(r);render();toast('بازیابی شد.')}});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let r=records.find(x=>x.id===b.dataset.edit);if(!r)return;r.type==='habit'?formFor('habit',r):formFor(r.type,r)});document.querySelectorAll('[data-habit]').forEach(b=>b.onclick=async()=>{let h=records.find(x=>x.id===b.dataset.habit),x=type('habitLog').find(l=>l.data.habitId===h.id&&l.date===today());if(x)await trash(x);else await save('habitLog',{habitId:h.id,completed:true},today());render()});let nb=$('[data-newhabit]');if(nb)nb.onclick=()=>formFor('habit');let ex=$('[data-export]');if(ex)ex.onclick=exportJSON;let im=$('[data-import]');if(im)im.onclick=importJSON;document.querySelectorAll('[data-openjournal]').forEach(b=>b.onclick=()=>openJournal(records.find(x=>x.id===b.dataset.openjournal)))}
function search(q){q=q.trim().toLowerCase();if(!q)return;let hits=active().filter(r=>r.type!=='journal'&&JSON.stringify(r.data).toLowerCase().includes(q));if(!hits.length)return toast('موردی پیدا نشد.');tab=hits.some(r=>r.type.startsWith('expense')||['income','transfer','fee'].includes(r.type))?'finance':hits.some(r=>r.type==='event')?'events':'more';render();toast(`${hits.length} مورد پیدا شد.`)}
function exportJSON(){let data={format:'personal-life-planner-export',version:'final-1',exportedAt:new Date().toISOString(),records};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`life-planner-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('خروجی JSON ساخته شد.')}
function importJSON(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{try{let f=i.files[0],d=JSON.parse(await f.text());if(!Array.isArray(d.records))throw 0;let n=0;for(let r of d.records)if(r.id&&!records.some(x=>x.id===r.id)){await put(r);records.push(r);n++}render();toast(`${n} رکورد وارد شد.`)}catch{toast('فایل JSON معتبر نیست.')}};i.click()}
function appLock(){toast('برای حفظ حریم خصوصی، از قفل خود iPhone استفاده کنید.')}
(async()=>{try{await openDB();records=await getAll();layout();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){document.body.innerHTML='<div class="panel center" style="margin:30px"><h2>⚠️ مشکل در بازکردن اطلاعات</h2><p>اطلاعات شما حذف نشده است.</p><button class="btn primary" onclick="location.reload()">تلاش مجدد</button></div>'}})();
})();
